
###################################################################################
###################################################################################
input_boolean:
  tgl_security_garage_activate: #This switch will activate or not the alarms at the garage
    name: tgl_security_garage_activate
    icon: mdi:security 
    initial: "on"

  tgl_security_garage_perimeter_activate: #This switch will activate only the perimeter sensors and not the inside sensors like motion sensors.
    name: tgl_security_garage_perimeter_activate
    icon: mdi:security
    initial: "on"    

  tgl_security_forced_garage_activate: #This switch will force the activation of the alarm in the garage despite the state of the sensors.
    name: tgl_security_forced_garage_activate
    icon: mdi:security 
    # initial: "off"

###################################################################################
###################################################################################
input_select:
  garage_alarm_status:
    name: Garage alarm status
    options:
    - "off"
    - "armed"
    - "activate"
    # initial: "off"
    icon: mdi:alarm-bell    

###################################################################################
###################################################################################
timer:
  timer_security_delay_garage_activation:
    name: Timer Security Delay garage activation
    icon: mdi:camera-timer
    duration: "00:01:00"
    restore: true           


###################################################################################
###################################################################################
# automation:
###################################################################################
  # - alias: Security MainFloor Check Sensors are close
  #   description: ""
  #   trigger:
  #     - platform: state
  #       entity_id:
  #         - sensor.01_snzb_03_basementhall_motion
  #       to: "1"
  #   condition: []
  #   action:
  #   - service: notify.ha_rabbitbot
  #     data:
  #       message: Motion sensor 01-SNZB-03-BasementHall-Motion Activated
  #       title: Turn lights on
  #   mode: single



# service: telegram_bot.send_photo
# data:
#   url: http://192.168.1.151:8080/photoaf.jpg
#   caption: My image
#   message_tag: msg_to_edit
#   username: !secret android_ip_webcam_user
#   password: !secret android_ip_webcam_pass


binary_sensor.192_168_1_146_motion_active