###################################################################################
###################################################################################
# HELPERS
###################################################################################   

input_number:
  number_garage_south_ampere_output:
    name: "Set MPPT 150/70 - GarageSouth Ampere output"
    icon: mdi:current-dc
    min: 0
    max: 70
    #initial: 14
    step: 1
    # mode: box
    unit_of_measurement: A   

  number_garage_north_ampere_output:
    name: "Set MPPT 150/70tr - GarageNorth Ampere output"
    icon: mdi:current-dc
    min: 0
    max: 70
    #initial: 14
    step: 1
    # mode: box
    unit_of_measurement: A      

###################################################################################
###################################################################################
# AUTOMATIONS
###################################################################################    

automation:    
  - alias: "MPPT GarageSouth Ampere output" 
    trigger:
      platform: state
      entity_id: input_number.number_garage_south_ampere_output
    action:
      - service: mqtt.publish
        data_template:
          topic: "victron_env/W/c0619ab3baad/solarcharger/289/Settings/ChargeCurrentLimit"
          payload: '{"value": {{ states("input_number.number_garage_south_ampere_output") | int }} }'

  - alias: "MPPT 150/70tr - GarageNorth Ampere output" 
    trigger:
      platform: state
      entity_id: input_number.number_garage_north_ampere_output
    action:
      - service: mqtt.publish
        data_template:
          topic: "victron_env/W/c0619ab3baad/solarcharger/290/Settings/ChargeCurrentLimit"
          payload: '{"value": {{ states("input_number.number_garage_north_ampere_output") | int }} }'          
