###################################################################################
###################################################################################
# input_boolean:
###################################################################################

###################################################################################
###################################################################################
# input_datetime:
###################################################################################

###################################################################################
###################################################################################
# input_number:
###################################################################################

###################################################################################
###################################################################################
# input_select:
###################################################################################

###################################################################################
###################################################################################
# mqtt:
###################################################################################
#  binary_sensor: #mqtt_binary_sensor
###################################################################################  
#  number: #mqtt_number
###################################################################################  
#  sensor: #mqtt_sensor
###################################################################################  
#  switch: #mqtt_switch
###################################################################################  

###################################################################################
###################################################################################
# sensor:
###################################################################################

###################################################################################
###################################################################################
# template:
###################################################################################
  # - sensor:


###################################################################################
###################################################################################
# timer:
###################################################################################

###################################################################################
###################################################################################
# To check the utility meters, go to Settings/Devices&Services/Entities.  In the tab Helpers this will not appear.
# utility_meter:
###################################################################################

###################################################################################
###################################################################################
# automation:
###################################################################################
# Since home assistant only manage in the automations the uuid IDs for the sensors and entities, i recommend to create directly in home assistant the automations.
# is so dificult to maintain the automations full of uuids instead of the sensors names or the sensors unique_id.

