####################################################################################################################
############# MPPT - MQTT - Numbers
####################################################################################################################

# MPPT GarageSouth 150-70 - Adjust the maximun ampere to charge batteries
###################################################################################
# 2024-08-04-Since the update to the cerbo, this sensor is not working anymore. Please go to "packages/pck_solar_production/pck_solar_production_mppt_adjust_amps_charger.yaml"
  # - unique_id: victron_solar_charger_garage_south_ampere_output
  #   name: Ampere output
  #   command_topic: "victron_env/W/c0619ab3baad/solarcharger/289/Settings/ChargeCurrentLimit"
  #   #command_template: '{"value": {{states("number.mppt_150_70_garagesouth_ampere_output")| int }} }'
  #   # payload_template: '{"value": {{ states('input_number.target_temp') | int }} }'    
  #   # payload_template: '{{ states.sensor.speedtest_download.state }}'
  #   # payload_on: '{"value": 1}' # Victron uses the 1 to start the mppt to charge the batteries.
  #   # payload_off: '{"value": 4}' # Victron uses the 4 to stop the mppt to not charge the batteries.
  #   state_topic: "victron_env/N/c0619ab3baad/solarcharger/289/Settings/ChargeCurrentLimit"
  #   value_template: "{{ value_json.value | int }}"
  #   min: 0
  #   max: 70
  #   device_class: current
  #   unit_of_measurement: A
  #   icon: mdi:current-dc
  #   device: {
  #     identifiers: [
  #       "Victron MPPT 150/70"
  #     ],
  #     manufacturer: "Victron Energy",
  #     model: "MPPT 150/70",
  #     name: "MPPT 150/70 - GarageSouth"}  

# MPPT GarageSouth 150-70 - Adjust the maximun ampere to charge batteries
###################################################################################
  - unique_id: victron_solar_charger_garage_south_ampere_output
    name: Ampere output
    state_topic: "victron_env/N/c0619ab3baad/solarcharger/289/Settings/ChargeCurrentLimit"
    command_topic: "victron_env/W/c0619ab3baad/solarcharger/289/Settings/ChargeCurrentLimit"
    value_template: "{{ value_json.value | int }}"
    min: 0
    max: 70
    device_class: current
    unit_of_measurement: A
    icon: mdi:current-dc
    mode: box    
    device: {
      identifiers: [
        "Victron MPPT 150/70"
      ],
      manufacturer: "Victron Energy",
      model: "MPPT 150/70",
      name: "MPPT 150/70 - GarageSouth"}    


# MPPT GarageNorth 150-70 - Adjust the maximun ampere to charge batteries
###################################################################################
# 2024-08-04-Since the update to the cerbo, this sensor is not working anymore. Please go to "packages/pck_solar_production/pck_solar_production_mppt_adjust_amps_charger.yaml"
  # - unique_id: victron_solar_charger_garage_north_ampere_output
  #   name: Ampere output
  #   command_topic: "victron_env/W/c0619ab3baad/solarcharger/290/Settings/ChargeCurrentLimit"
  #   # payload_template: '{{ states.sensor.speedtest_download.state }}'
  #   # payload_on: '{"value": 1}' # Victron uses the 1 to start the mppt to charge the batteries.
  #   # payload_off: '{"value": 4}' # Victron uses the 4 to stop the mppt to not charge the batteries.
  #   state_topic: "victron_env/N/c0619ab3baad/solarcharger/290/Settings/ChargeCurrentLimit"
  #   value_template: "{{ value_json.value | int }}"
  #   min: 0
  #   max: 70
  #   device_class: current
  #   unit_of_measurement: A
  #   icon: mdi:current-dc
  #   device: {
  #     identifiers: [
  #       "Victron MPPT 150/70tr"
  #     ],
  #     manufacturer: "Victron Energy",
  #     model: "MPPT 150/70tr",
  #     name: "MPPT 150/70tr - GarageNorth"}  

# MPPT GarageNorth 150-70 - Adjust the maximun ampere to charge batteries
###################################################################################
  - unique_id: victron_solar_charger_garage_north_ampere_output
    name: Ampere output
    state_topic: "victron_env/N/c0619ab3baad/solarcharger/290/Settings/ChargeCurrentLimit"
    command_topic: "victron_env/W/c0619ab3baad/solarcharger/290/Settings/ChargeCurrentLimit"    
    value_template: "{{ value_json.value | int }}"
    min: 0
    max: 70
    device_class: current
    unit_of_measurement: A
    icon: mdi:current-dc
    mode: box    
    device: {
      identifiers: [
        "Victron MPPT 150/70tr"
      ],
      manufacturer: "Victron Energy",
      model: "MPPT 150/70tr",
      name: "MPPT 150/70tr - GarageNorth"}    
