####################################################################################################################
############# CERBO
####################################################################################################################

#Cerbo General Alarm
- unique_id: victron_cerbo_buzzer
  name: Cerbo System Status
  state_topic: "victron_env/N/c0619ab3baad/system/0/Buzzer/State" 
  value_template: "{{ value_json.value }}"
  payload_on: "1"
  payload_off: "0"
  icon: mdi:information-outline
  device_class: problem
  device: {
    identifiers: [
      "Victron Cerbo GX"
    ],
    manufacturer: "Victron Energy",
    model: "Cerbo GX",
    name: "Cerbo GX"}

#Cerbo Laden erlaubt
- unique_id: cerbo_allow_to_charge
  name: Cerbo Allow to charge
  state_topic: "victron_env/N/c0619ab3baad/system/0/SystemState/ChargeDisabled"
  value_template: "{{ value_json.value }}"
  payload_on: "0"
  payload_off: "1"
  device: {
    identifiers: [
      "Victron Cerbo GX"
    ],
    manufacturer: "Victron Energy",
    model: "Cerbo GX",
    name: "Cerbo GX"}

#Cerbo Entaden erlaubt
- unique_id: cerbo_allow_to_discharge
  name: Cerbo Allow to discharge
  state_topic: "victron_env/N/c0619ab3baad/system/0/SystemState/DischargeDisabled"
  value_template: "{{ value_json.value }}"
  payload_on: "0"
  payload_off: "1"
  device: {
    identifiers: [
      "Victron Cerbo GX"
    ],
    manufacturer: "Victron Energy",
    model: "Cerbo GX",
    name: "Cerbo GX"}
