#Es el 05-ESP32, el 02-ESP32 y el 04-ESP32 parece que están rotos.
esphome:
  name: "02-dalybmss-esp32"
  friendly_name: 02-DalyBMSs-ESP32
  # 192.168.1.105  

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Tbp+psEOkIQa/YJKsm6FelMd8/fGN+2K3HlKyMp4RdE=" 

web_server:
  port: 80

ota:

# Multiple networks with DHCP
wifi:
  networks:  
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: RoLu_dhcp_EXT
    password: !secret dhcp_ext
  - ssid: RoLu_dhcp
    password: !secret rolu_dhcp  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "02-dalybmss-esp32_ap"
    password: !secret wifi_password

captive_portal:

################################
# Example configuration entry
# switch:
#   - platform: gpio
#     pin: 22
#     name: "Rele test"

################################
################################
text_sensor:
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results
  - platform: daly_bms
    status:
      name: "BMS Status"      


################################
################################
# Example configuration entry (ESP8266)
#UART
uart:
  tx_pin: GPIO22
  rx_pin: GPIO23
  baud_rate: 9600

daly_bms:
  update_interval: 15s

sensor:
  - platform: daly_bms
    voltage:
      name: "Battery Voltage"
    current:
      name: "Battery Current"
    battery_level:
      name: "Battery Level"
    max_cell_voltage:
      name: "Max Cell Voltage"
    max_cell_voltage_number:
      name: "Max Cell Voltage Number"
    min_cell_voltage:
      name: "Min Cell Voltage"
    min_cell_voltage_number:
      name: "Min Cell Voltage Number"
    max_temperature:
      name: "Max Temperature"
    max_temperature_probe_number:
      name: "Max Temperature Probe Number"
    min_temperature:
      name: "Min Temperature"
    min_temperature_probe_number:
      name: "Min Temperature Probe Number"
    remaining_capacity:
      name: "Remaining Capacity"
    cells_number:
      name: "Cells Number"
    temperature_1:
      name: "Temperature 1"
    # temperature_2:
    #   name: "Temperature 2"
    cell_1_voltage:
      name: "Cell 1 Voltage"
    cell_2_voltage:
      name: "Cell 2 Voltage"
    cell_3_voltage:
      name: "Cell 3 Voltage"
    # cell_4_voltage:
    #   name: "Cell 4 Voltage"

binary_sensor:
  - platform: daly_bms
    charging_mos_enabled:
      name: "Charging MOS"
    discharging_mos_enabled:
      name: "Discharging MOS"
    
    