substitutions:
  name: 03-esp32-christmastlights
  friendly_name: 03-ESP32-ChristmastLights
  esp_ip: 192.168.1.242    
  name_jk: "jkbms"
  device_description: "Monitor a JK-BMS via BLE/UART"
  external_components_source: github://syssi/esphome-jk-bms@main
  tx_pin: GPIO22
  rx_pin: GPIO23
 ##############################
  # Bluetooth connection
  # Please use "JK02_24S" if you own a old JK-BMS < hardware version 11.0 (hardware version >= 6.0 and < 11.0)
  # Please use "JK02_32S" if you own a new JK-BMS >= hardware version 11.0 (f.e. JK-B2A8S20P hw 11.XW, sw 11.26)
  # Please use "JK04" if you have some old JK-BMS <= hardware version 3.0 (f.e. JK-B2A16S hw 3.0, sw. 3.3.0)
  protocol_version: JK02_32S  
  jk_bms_bluetooth_mac_address: C8:47:80:01:CE:38

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: ${device_description} 
  project:
    name: "syssi.esphome-jk-bms"
    version: 2.0.0 

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
# logger:

api:
  encryption:
    key: "0rbsyNOcTtdy893hYN288K106lfsOuf3XpQ7V2keEOA="    

web_server:
  port: 80

ota:
  on_begin:
    then:
      - switch.turn_off: ble_client_switch0
      - logger.log: "BLE connection suspended for OTA update"

# Multiple networks with DHCP
wifi:
  networks:
  - ssid: !secret wifi_ssid
    password: !secret wifi_password
  - ssid: RoLu_dhcp_EXT
    password: !secret dhcp_ext
  - ssid: RoLu_dhcp
    password: !secret rolu_dhcp

  # Optional manual IP
  manual_ip:
    static_ip: ${esp_ip}
    gateway: 192.168.1.1
    subnet: 255.255.255.0  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "03-esp32-christmastlights_ap"
    password: "03-esp32-christmastlights_ap"

captive_portal:

# Enable logging
logger:
  baud_rate: 0
  level: DEBUG
  logs:
    esp32_ble_tracker: INFO
    jk_bms_ble: INFO
    scheduler: DEBUG
    component: DEBUG
    sensor: INFO
    api.service: INFO
    api: INFO
    number: INFO

debug:
  update_interval: 10s    

# If you use Home Assistant please remove this `mqtt` section and uncomment the `api` component!
# The native API has many advantages over MQTT: https://esphome.io/components/api.html#advantages-over-mqtt
# mqtt:
#   broker: !secret mqtt_host
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   id: mqtt_client

external_components:
  - source: ${external_components_source}
    refresh: 0s  

### BLE

esp32_ble_tracker:
  on_ble_advertise:
    then:
      - lambda: |-
          if (x.get_name().rfind("JK-", 0) == 0 || x.get_name().rfind("JK_", 0) == 0) {
            ESP_LOGI("ble_adv", "New JK-BMS found");
            ESP_LOGI("ble_adv", "  Name: %s", x.get_name().c_str());
            ESP_LOGI("ble_adv", "  MAC address: %s", x.address_str().c_str());
            ESP_LOGD("ble_adv", "  Advertised service UUIDs:");
            for (auto uuid : x.get_service_uuids()) {
              ESP_LOGD("ble_adv", "    - %s", uuid.to_string().c_str());
            }
          }

ble_client:
  - mac_address: ${jk_bms_bluetooth_mac_address}
    id: client0

jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${protocol_version}
    throttle: 5s
    id: bmsble0    

################ BINARY_SENSOR ######################
binary_sensor:
  - platform: jk_bms_ble
    balancing:
      name: "${name_jk} balancing"
    charging:
      name: "${name_jk} charging"
    discharging:
      name: "${name_jk} discharging"
#    heating:
#      name: "${name_jk} heating"
    online_status:
      name: "${name_jk} online status"    

################ BUTTONS ###############################
button:
  - platform: jk_bms_ble
    retrieve_settings:
      name: "${name_jk} retrieve settings"
    retrieve_device_info:
      name: "${name_jk} retrieve device info"      

################ NUMBER ###############################
number:
  - platform: jk_bms_ble
    jk_bms_ble_id: bmsble0
    balance_trigger_voltage:
      name: "${name_jk} balance trigger voltage"
    cell_count:
      name: "${name_jk} cell count"
    total_battery_capacity:
      name: "${name_jk} total battery capacity"
    cell_voltage_overvoltage_protection:
      name: "${name_jk} cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      name: "${name_jk} cell voltage overvoltage recovery"
    cell_voltage_undervoltage_protection:
      name: "${name_jk} cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      name: "${name_jk} cell voltage undervoltage recovery"
    balance_starting_voltage:
      name: "${name_jk} balance starting voltage"
    voltage_calibration:
      name: "${name_jk} voltage calibration"
    current_calibration:
      name: "${name_jk} current calibration"
    power_off_voltage:
      name: "${name_jk} power off voltage"
    max_balance_current:
      name: "${name_jk} max balance current"
    max_charge_current:
      name: "${name_jk} max charge current"
    max_discharge_current:
      name: "${name_jk} max discharge current"      

############### SENSOR  ###########################
sensor:
  - platform: wifi_signal
    name: "${name_jk} WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "${name_jk} uptime"
    update_interval: 1s
  - platform: debug
    free:
      name: "Heap Free"
############## JK BMS SENSOR ######################
  - platform: jk_bms_ble
    jk_bms_ble_id: bmsble0
    min_cell_voltage:
      name: "${name_jk} min cell voltage"
    max_cell_voltage:
      name: "${name_jk} max cell voltage"
    min_voltage_cell:
      name: "${name_jk} min voltage cell"
    max_voltage_cell:
      name: "${name_jk} max voltage cell"
    delta_cell_voltage:
      name: "${name_jk} delta cell voltage"
    average_cell_voltage:
      name: "${name_jk} average cell voltage"
    cell_voltage_1:
      name: "${name_jk} cell voltage 1"
    cell_voltage_2:
      name: "${name_jk} cell voltage 2"
    cell_voltage_3:
      name: "${name_jk} cell voltage 3"
    cell_voltage_4:
      name: "${name_jk} cell voltage 4"
    # cell_voltage_5:
    #   name: "${name_jk} cell voltage 5"
    # cell_voltage_6:
    #   name: "${name_jk} cell voltage 6"
    # cell_voltage_7:
    #   name: "${name_jk} cell voltage 7"
    # cell_voltage_8:
    #   name: "${name_jk} cell voltage 8"
    # cell_voltage_9:
    #   name: "${name_jk} cell voltage 9"
    # cell_voltage_10:
    #   name: "${name_jk} cell voltage 10"
    # cell_voltage_11:
    #   name: "${name_jk} cell voltage 11"
    # cell_voltage_12:
    #   name: "${name_jk} cell voltage 12"
    # cell_voltage_13:
    #   name: "${name_jk} cell voltage 13"
    # cell_voltage_14:
    #   name: "${name_jk} cell voltage 14"
    # cell_voltage_15:
    #   name: "${name_jk} cell voltage 15"
    # cell_voltage_16:
    #   name: "${name_jk} cell voltage 16"
    cell_resistance_1:
      name: "${name_jk} cell resistance 1"
    cell_resistance_2:
      name: "${name_jk} cell resistance 2"
    cell_resistance_3:
      name: "${name_jk} cell resistance 3"
    cell_resistance_4:
      name: "${name_jk} cell resistance 4"
    # cell_resistance_5:
    #   name: "${name_jk} cell resistance 5"
    # cell_resistance_6:
    #   name: "${name_jk} cell resistance 6"
    # cell_resistance_7:
    #   name: "${name_jk} cell resistance 7"
    # cell_resistance_8:
    #   name: "${name_jk} cell resistance 8"
    # cell_resistance_9:
    #   name: "${name_jk} cell resistance 9"
    # cell_resistance_10:
    #   name: "${name_jk} cell resistance 10"
    # cell_resistance_11:
    #   name: "${name_jk} cell resistance 11"
    # cell_resistance_12:
    #   name: "${name_jk} cell resistance 12"
    # cell_resistance_13:
    #   name: "${name_jk} cell resistance 13"
    # cell_resistance_14:
    #   name: "${name_jk} cell resistance 14"
    # cell_resistance_15:
    #   name: "${name_jk} cell resistance 15"
    # cell_resistance_16:
    #   name: "${name_jk} cell resistance 16"
    total_voltage:
      name: "${name_jk} total voltage"
    current:
      name: "${name_jk} current"
    heating_current:
      name: "${name_jk} heating current"
    power:
      name: "${name_jk} power"
    charging_power:
      name: "${name_jk} charging power"
    discharging_power:
      name: "${name_jk} discharging power"
    temperature_sensor_1:
      name: "${name_jk} temperature sensor 1"
    temperature_sensor_2:
      name: "${name_jk} temperature sensor 2"
    power_tube_temperature:
      name: "${name_jk} power tube temperature"
    state_of_charge:
      name: "${name_jk} state of charge"
    capacity_remaining:
      name: "${name_jk} capacity remaining"
    total_battery_capacity_setting:
      name: "${name_jk} total battery capacity setting"
    charging_cycles:
      name: "${name_jk} charging cycles"
    total_charging_cycle_capacity:
      name: "${name_jk} total charging cycle capacity"
    total_runtime:
      name: "${name_jk} total runtime"
    balancing_current:
      name: "${name_jk} balancing current"
    errors_bitmask:
      name: "${name_jk} errors bitmask" 

############### SWITCH  ###########################

################################
# Example configuration entry
switch:
  - platform: gpio
    pin: 22
    name: "Rele test"
    ##############################
  - platform: jk_bms_ble
    charging:
      name: "${name_jk} charging"
    discharging:
      name: "${name_jk} discharging"
    balancer:
      name: "${name_jk} balancer"
  - platform: ble_client
    ble_client_id: client0
    id: ble_client_switch0
    name: "${name_jk} enable bluetooth connection"    


################################
############### TEXT_SENSOR  ###########################
################################
text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results
    dns_address:
      name: ESP DNS Address      
####################################################
  - platform: jk_bms_ble
    errors:
      name: "${name_jk} errors"
    total_runtime_formatted:
      name: "${name_jk} total runtime formatted"
  - platform: jk_bms
    jk_bms_id: bms0
    operation_mode:
      name: "${name_jk} operation mode"      
    