###################################################################################
###################################################################################
# 06 - Bought on Amazon the 2024-07-26
###################################################################################
# History
# 2024-07-28 - NO TENGO HUEVOS A CONFIGURAR BIEN EL SISSY CON BLUE TOOTH. ASI QUE ME HE PASADO AL DEL RS485
###################################################################################


substitutions:
  name: "06-esp32-jk-bms-hub-bt-01"
  friendly_name: 06-ESP32-JK-BMS-hub-BT-01  
  esp_ip: 192.168.1.241     
  device_description: "Monitor and control a JK-BMS via bluetooth"
  external_components_source: github://syssi/esphome-jk-bms@main  
  # #JK_PB2A16S20P-00
  name_jk_shelf_01: "shelf-jkbms-01"
  mac_address_shelf_01: C8:47:80:10:05:8E 
  # #JK2A8S20P-PoW
  # name_jk_shelf_01: "shelf-jkbms-01"
  # mac_address_shelf_01: C8:47:80:07:53:45

  # JK_PB2A16S20P-00 C8:47:80:10:05:8E
  # JK2A8S20P-PoW C8:47:80:07:53:45
  # JK2A8S20P-Pri C8:47:80:01:CE:38  
  
  # Please use "JK02_24S" if you own a old JK-BMS < hardware version 11.0 (hardware version >= 6.0 and < 11.0)
  # Please use "JK02_32S" if you own a new JK-BMS >= hardware version 11.0 (f.e. JK-B2A8S20P hw 11.XW, sw 11.26)
  # Please use "JK04" if you have some old JK-BMS <= hardware version 3.0 (f.e. JK-B2A16S hw 3.0, sw. 3.3.0)
  # protocol_version: JK02_32S # For the non inverters JK
  protocol_version: JK02_24S # For JK-Inverters(JK_PBxxx)
  

esphome:
  name: ${name}
  friendly_name: ${friendly_name}  
  comment: ${device_description}
  min_version: 2024.6.0
  name_add_mac_suffix: false  
  project:
    name: "syssi.esphome-jk-bms"
    version: 2.0.0

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable Home Assistant API
# If you don't use Home Assistant please remove this `api` section and uncomment the `mqtt` component!
api:  

# To have a "next url" for improv serial
web_server:
  port: 80

# Allow Over-The-Air updates
ota:
  platform: esphome
  on_begin:
    then:
      - switch.turn_off: ble_client_switch0
      - logger.log: "BLE connection suspended for OTA update"  

# Multiple networks with DHCP. The secrets file is inside the ESPHome section, not in the main secret.yaml file of home assistant
wifi:
  networks:
  - ssid: !secret wifi_ssid_main
    password: !secret wifi_main_password
  - ssid: !secret wifi_ssid_secondary
    password: !secret wifi_secondary_password
  - ssid: !secret wifi_ssid_dhcp
    password: !secret wifi_ssid_dhcp_password
  - ssid: !secret wifi_ssid_dhcp_ext
    password: !secret wifi_ssid_dhcp_ext_password

  # Optional manual IP
  manual_ip:
    static_ip: ${esp_ip}
    gateway: 192.168.1.1
    subnet: 255.255.255.0   

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "06-esp32-jk-bms-hub-bt-01_ap"
    password: "06-esp32-jk-bms-hub-bt-01_ap"

logger:
  level: DEBUG
  # level: VERY_VERBOSE
  # logs:
  #   esp32_ble_tracker: VERY_VERBOSE
  #   jk_bms_ble: VERY_VERBOSE
  #   scheduler: DEBUG
  #   component: DEBUG
  #   sensor: DEBUG
  #   mqtt: INFO
  #   mqtt.idf: INFO
  #   mqtt.component: INFO
  #   mqtt.sensor: INFO
  #   mqtt.switch: INFO
  #   api.service: INFO
  #   api: INFO      

debug:
  update_interval: 5s   

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
# captive_portal:

# Allow provisioning Wi-Fi via serial
improv_serial:

# dashboard_import:
#   package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
#   import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
# esp32_improv:
#   authorizer: none

external_components:
  - source: ${external_components_source}
    refresh: 0s

# mqtt:
#   broker: !secret mqtt_host
#   username: !secret mqtt_username
#   password: !secret mqtt_password
#   id: mqtt_client

esp32_ble_tracker:
  on_ble_advertise:
    then:
      - lambda: |-
          if (x.get_name().rfind("JK", 0) == 0 || x.get_name().rfind("JK_", 0) == 0) {
            ESP_LOGI("ble_adv", "New JK-BMS found");
            ESP_LOGI("ble_adv", "  Name: %s", x.get_name().c_str());
            ESP_LOGI("ble_adv", "  MAC address: %s", x.address_str().c_str());
            ESP_LOGD("ble_adv", "  Advertised service UUIDs:");
            for (auto uuid : x.get_service_uuids()) {
              ESP_LOGD("ble_adv", "    - %s", uuid.to_string().c_str());
            }
          }

ble_client:
  - mac_address: ${mac_address_shelf_01}
    id: client0

jk_bms_ble:
  - ble_client_id: client0
    protocol_version: ${protocol_version}
    throttle: 15s
    id: bms0

# ###################################################
# BINARY SENSORS
# ###################################################
binary_sensor:
  - platform: jk_bms_ble
    balancing:
      name: "${name_jk_shelf_01} balancing"
    charging:
      name: "${name_jk_shelf_01} charging"
    discharging:
      name: "${name_jk_shelf_01} discharging"
    heating:
      name: "${name_jk_shelf_01} heating"
    online_status:
      name: "${name_jk_shelf_01} online status"

# ###################################################
# BUTTONS
# ###################################################
button:
  - platform: jk_bms_ble
    retrieve_settings:
      name: "${name_jk_shelf_01} retrieve settings"
    retrieve_device_info:
      name: "${name_jk_shelf_01} retrieve device info"

###################################################
# NUMBERS
###################################################
number:
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    balance_trigger_voltage:
      name: "${name_jk_shelf_01} balance trigger voltage"
    cell_count:
      name: "${name_jk_shelf_01} cell count"
    total_battery_capacity:
      name: "${name_jk_shelf_01} total battery capacity"
    cell_voltage_overvoltage_protection:
      name: "${name_jk_shelf_01} cell voltage overvoltage protection"
    cell_voltage_overvoltage_recovery:
      name: "${name_jk_shelf_01} cell voltage overvoltage recovery"
    cell_voltage_undervoltage_protection:
      name: "${name_jk_shelf_01} cell voltage undervoltage protection"
    cell_voltage_undervoltage_recovery:
      name: "${name_jk_shelf_01} cell voltage undervoltage recovery"
    balance_starting_voltage:
      name: "${name_jk_shelf_01} balance starting voltage"
    voltage_calibration:
      name: "${name_jk_shelf_01} voltage calibration"
    current_calibration:
      name: "${name_jk_shelf_01} current calibration"
    power_off_voltage:
      name: "${name_jk_shelf_01} power off voltage"
    max_balance_current:
      name: "${name_jk_shelf_01} max balance current"
    max_charge_current:
      name: "${name_jk_shelf_01} max charge current"
    max_discharge_current:
      name: "${name_jk_shelf_01} max discharge current"
    smart_sleep_voltage:
      name: "${name_jk_shelf_01} smart sleep voltage"
    cell_soc100_voltage:
      name: "${name_jk_shelf_01} cell soc100 voltage"
    cell_soc0_voltage:
      name: "${name_jk_shelf_01} cell soc0 voltage"
    cell_request_charge_voltage:
      name: "${name_jk_shelf_01} cell request charge voltage"
    cell_request_float_voltage:
      name: "${name_jk_shelf_01} cell request float voltage"
    charge_overcurrent_protection_delay:
      name: "${name_jk_shelf_01} charge overcurrent protection delay"
    charge_overcurrent_protection_recovery_time:
      name: "${name_jk_shelf_01} charge overcurrent protection recovery time"
    discharge_overcurrent_protection_delay:
      name: "${name_jk_shelf_01} discharge overcurrent protection delay"
    discharge_overcurrent_protection_recovery_time:
      name: "${name_jk_shelf_01} discharge overcurrent protection recovery time"
    short_circuit_protection_delay:
      name: "${name_jk_shelf_01} short circuit protection delay"
    short_circuit_protection_recovery_time:
      name: "${name_jk_shelf_01} short circuit protection recovery time"
    charge_overtemperature_protection:
      name: "${name_jk_shelf_01} charge overtemperature protection"
    charge_overtemperature_protection_recovery:
      name: "${name_jk_shelf_01} charge overtemperature protection recovery"
    discharge_overtemperature_protection:
      name: "${name_jk_shelf_01} discharge overtemperature protection"
    discharge_overtemperature_protection_recovery:
      name: "${name_jk_shelf_01} discharge overtemperature protection recovery"
    charge_undertemperature_protection:
      name: "${name_jk_shelf_01} charge undertemperature protection"
    charge_undertemperature_protection_recovery:
      name: "${name_jk_shelf_01} charge undertemperature protection recovery"
    power_tube_overtemperature_protection:
      name: "${name_jk_shelf_01} power tube overtemperature protection"
    power_tube_overtemperature_protection_recovery:
      name: "${name_jk_shelf_01} power tube overtemperature protection recovery"      


# ###################################################
# SENSOR
# ###################################################
sensor:
  - platform: wifi_signal
    name: "${name} WiFi Signal"
    update_interval: 60s
  - platform: uptime
    name: "${name} uptime"
    update_interval: 1s
  # - platform: debug
  #   free:
  #     name: "Heap Free"
# # ###################################################
  - platform: jk_bms_ble
    jk_bms_ble_id: bms0
    min_cell_voltage:
      name: "${name_jk_shelf_01} min cell voltage"
    max_cell_voltage:
      name: "${name_jk_shelf_01} max cell voltage"
    min_voltage_cell:
      name: "${name_jk_shelf_01} min voltage cell"
    max_voltage_cell:
      name: "${name_jk_shelf_01} max voltage cell"
    delta_cell_voltage:
      name: "${name_jk_shelf_01} delta cell voltage"
    average_cell_voltage:
      name: "${name_jk_shelf_01} average cell voltage"
    cell_voltage_1:
      name: "${name_jk_shelf_01} cell voltage 1"
    cell_voltage_2:
      name: "${name_jk_shelf_01} cell voltage 2"
    cell_voltage_3:
      name: "${name_jk_shelf_01} cell voltage 3"
    cell_voltage_4:
      name: "${name_jk_shelf_01} cell voltage 4"
    cell_voltage_5:
      name: "${name_jk_shelf_01} cell voltage 5"
    cell_voltage_6:
      name: "${name_jk_shelf_01} cell voltage 6"
    cell_voltage_7:
      name: "${name_jk_shelf_01} cell voltage 7"
    cell_voltage_8:
      name: "${name_jk_shelf_01} cell voltage 8"
    cell_voltage_9:
      name: "${name_jk_shelf_01} cell voltage 9"
    cell_voltage_10:
      name: "${name_jk_shelf_01} cell voltage 10"
    cell_voltage_11:
      name: "${name_jk_shelf_01} cell voltage 11"
    cell_voltage_12:
      name: "${name_jk_shelf_01} cell voltage 12"
    cell_voltage_13:
      name: "${name_jk_shelf_01} cell voltage 13"
    cell_voltage_14:
      name: "${name_jk_shelf_01} cell voltage 14"
    cell_voltage_15:
      name: "${name_jk_shelf_01} cell voltage 15"
    cell_voltage_16:
      name: "${name_jk_shelf_01} cell voltage 16"
    # cell_voltage_17:
    #   name: "${name_jk_shelf_01} cell voltage 17"
    # cell_voltage_18:
    #   name: "${name_jk_shelf_01} cell voltage 18"
    # cell_voltage_19:
    #   name: "${name_jk_shelf_01} cell voltage 19"
    # cell_voltage_20:
    #   name: "${name_jk_shelf_01} cell voltage 20"
    # cell_voltage_21:
    #   name: "${name_jk_shelf_01} cell voltage 21"
    # cell_voltage_22:
    #   name: "${name_jk_shelf_01} cell voltage 22"
    # cell_voltage_23:
    #   name: "${name_jk_shelf_01} cell voltage 23"
    # cell_voltage_24:
    #   name: "${name_jk_shelf_01} cell voltage 24"
    cell_resistance_1:
      name: "${name_jk_shelf_01} cell resistance 1"
    cell_resistance_2:
      name: "${name_jk_shelf_01} cell resistance 2"
    cell_resistance_3:
      name: "${name_jk_shelf_01} cell resistance 3"
    cell_resistance_4:
      name: "${name_jk_shelf_01} cell resistance 4"
    cell_resistance_5:
      name: "${name_jk_shelf_01} cell resistance 5"
    cell_resistance_6:
      name: "${name_jk_shelf_01} cell resistance 6"
    cell_resistance_7:
      name: "${name_jk_shelf_01} cell resistance 7"
    cell_resistance_8:
      name: "${name_jk_shelf_01} cell resistance 8"
    cell_resistance_9:
      name: "${name_jk_shelf_01} cell resistance 9"
    cell_resistance_10:
      name: "${name_jk_shelf_01} cell resistance 10"
    cell_resistance_11:
      name: "${name_jk_shelf_01} cell resistance 11"
    cell_resistance_12:
      name: "${name_jk_shelf_01} cell resistance 12"
    cell_resistance_13:
      name: "${name_jk_shelf_01} cell resistance 13"
    cell_resistance_14:
      name: "${name_jk_shelf_01} cell resistance 14"
    cell_resistance_15:
      name: "${name_jk_shelf_01} cell resistance 15"
    cell_resistance_16:
      name: "${name_jk_shelf_01} cell resistance 16"
    # cell_resistance_17:
    #   name: "${name_jk_shelf_01} cell resistance 17"
    # cell_resistance_18:
    #   name: "${name_jk_shelf_01} cell resistance 18"
    # cell_resistance_19:
    #   name: "${name_jk_shelf_01} cell resistance 19"
    # cell_resistance_20:
    #   name: "${name_jk_shelf_01} cell resistance 20"
    # cell_resistance_21:
    #   name: "${name_jk_shelf_01} cell resistance 21"
    # cell_resistance_22:
    #   name: "${name_jk_shelf_01} cell resistance 22"
    # cell_resistance_23:
    #   name: "${name_jk_shelf_01} cell resistance 23"
    # cell_resistance_24:
    #   name: "${name_jk_shelf_01} cell resistance 24"
    total_voltage:
      name: "${name_jk_shelf_01} total voltage"
    current:
      name: "${name_jk_shelf_01} current"
    heating_current:
      name: "${name_jk_shelf_01} heating current"
    power:
      name: "${name_jk_shelf_01} power"
    charging_power:
      name: "${name_jk_shelf_01} charging power"
    discharging_power:
      name: "${name_jk_shelf_01} discharging power"
    temperature_sensor_1:
      name: "${name_jk_shelf_01} temperature sensor 1"
    temperature_sensor_2:
      name: "${name_jk_shelf_01} temperature sensor 2"
    temperature_sensor_3:
      name: "${name_jk_shelf_01} temperature sensor 3"
    temperature_sensor_4:
      name: "${name_jk_shelf_01} temperature sensor 4"
    power_tube_temperature:
      name: "${name_jk_shelf_01} power tube temperature"
    balancing:
      name: "${name_jk_shelf_01} balancing"
    state_of_charge:
      name: "${name_jk_shelf_01} state of charge"
    capacity_remaining:
      name: "${name_jk_shelf_01} capacity remaining"
    total_battery_capacity_setting:
      name: "${name_jk_shelf_01} total battery capacity setting"
    charging_cycles:
      name: "${name_jk_shelf_01} charging cycles"
    total_charging_cycle_capacity:
      name: "${name_jk_shelf_01} total charging cycle capacity"
    total_runtime:
      name: "${name_jk_shelf_01} total runtime"
    balancing_current:
      name: "${name_jk_shelf_01} balancing current"
    errors_bitmask:
      name: "${name_jk_shelf_01} errors bitmask"
    emergency_time_countdown:
      name: "${name_jk_shelf_01} emergency time countdown"

# ###################################################
# SWITCH
# ###################################################

switch:
  - platform: jk_bms_ble
    charging:
      name: "${name_jk_shelf_01} charging"
    discharging:
      name: "${name_jk_shelf_01} discharging"
    balancer:
      name: "${name_jk_shelf_01} balancer"
    emergency:
      name: "${name_jk_shelf_01} emergency"
    heating:
      name: "${name_jk_shelf_01} heating"
    disable_temperature_sensors:
      name: "${name_jk_shelf_01} disable temperature sensors"
    display_always_on:
      name: "${name_jk_shelf_01} display always on"
    smart_sleep:
      name: "${name_jk_shelf_01} smart sleep"
    disable_pcl_module:
      name: "${name_jk_shelf_01} disable pcl module"
    timed_stored_data:
      name: "${name_jk_shelf_01} timed stored data"
    charging_float_mode:
      name: "${name_jk_shelf_01} charging float mode"
# ###################################################
  - platform: ble_client
    ble_client_id: client0
    id: ble_client_switch0
    name: "${name} enable bluetooth connection"


# ###################################################
# TEXT
# ###################################################

text_sensor:
  - platform: jk_bms_ble
    # operation_status:
    #   name: "${name_jk_shelf_01} operation status"
    total_runtime_formatted:
      name: "${name_jk_shelf_01} total runtime formatted"
    errors:
      name: "${name_jk_shelf_01} errors"
    # operation_mode:
    #   name: "${name_jk_shelf_01} operation mode"
    # battery_type:
    #   name: "${name_jk_shelf_01} battery type"
    # password:
    #   name: "${name_jk_shelf_01} password"
    # device_type:
    #   name: "${name_jk_shelf_01} device type"
    # software_version:
    #   name: "${name_jk_shelf_01} software version"
    # manufacturer:
    #   name: "${name_jk_shelf_01} manufacturer"
# ###################################################
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results
    dns_address:
      name: ESP DNS Address     
