####################################################################################################################
############# MPPT
####################################################################################################################

###################################################################################
###################################################################################
# MPPT GarageSouth 150-70 (SmartSolar Charger MPPT 150/70 rev2)
###################################################################################

# MPPT GarageSouth - Charger DC meassurements
###################################################################################
- unique_id: victron_solar_charger_garage_south_dc_voltage
  name: DC Voltage
  state_class: measurement
  device_class: voltage
  unit_of_measurement: V
  state_topic: "victron_env/N/c0619ab3baad/solarcharger/289/Dc/0/Voltage"
  value_template: "{{ value_json.value | round(2) }}"
  icon: mdi:lightning-bolt-circle
  device: {
    identifiers: [
      "Victron MPPT 150/70"
    ],
    manufacturer: "Victron Energy",
    model: "MPPT 150/70",
    name: "MPPT 150/70 - GarageSouth"}  

- unique_id: victron_solar_charger_garage_south_dc_current
  name: DC Current
  state_class: measurement
  device_class: current
  unit_of_measurement: A
  icon: mdi:current-dc
  state_topic: "victron_env/N/c0619ab3baad/solarcharger/289/Dc/0/Current"
  value_template: "{{ value_json.value | round(2) }}"
  device: {
    identifiers: [
      "Victron MPPT 150/70"
    ],
    manufacturer: "Victron Energy",
    model: "MPPT 150/70",
    name: "MPPT 150/70 - GarageSouth"}  

# MPPT GarageSouth - Photo Voltaic meassurements
###################################################################################
- unique_id: victron_solar_charger_garage_south_pv_voltage
  name: PV Voltage
  state_class: measurement
  device_class: voltage
  unit_of_measurement: V
  state_topic: "victron_env/N/c0619ab3baad/solarcharger/289/Pv/V"
  value_template: >
    {% if value_json.value | is_number %}
      {{ value_json.value | round(2) }}
    {% endif %}       
  icon: mdi:lightning-bolt-circle
  device: {
    identifiers: [
      "Victron MPPT 150/70"
    ],
    manufacturer: "Victron Energy",
    model: "MPPT 150/70",
    name: "MPPT 150/70 - GarageSouth"}    

# 2024-08-04-This do not exists in the cerboGX venusOS version, only in raspberry venusOS version.
# - unique_id: victron_solar_charger_garage_south_pv_current
#   name: PV Current
#   state_class: measurement
#   device_class: current
#   unit_of_measurement: A
#   state_topic: "victron_env/N/c0619ab3baad/solarcharger/289/Pv/I"
#   value_template: "{{ value_json.value | round(2) }}"
#   icon: mdi:current-dc
#   device: {
#     identifiers: [
#       "Victron MPPT 150/70"
#     ],
#     manufacturer: "Victron Energy",
#     model: "MPPT 150/70",
#     name: "MPPT 150/70 - GarageSouth"}

- unique_id: victron_solar_charger_garage_south_pv_power
  name: PV Power
  state_class: measurement
  device_class: power
  unit_of_measurement: W
  state_topic: "victron_env/N/c0619ab3baad/solarcharger/289/Yield/Power"
  value_template: >
    {% if value_json.value | is_number %}
      {{ value_json.value | round(2) }}
    {% endif %}       
  icon: mdi:solar-power
  device: {
    identifiers: [
      "Victron MPPT 150/70"
    ],
    manufacturer: "Victron Energy",
    model: "MPPT 150/70",
    name: "MPPT 150/70 - GarageSouth"}


# MPPT GarageSouth - Charger state 
###################################################################################
- unique_id: victron_solar_charger_garage_south_charger_state
  name: Charger State
  state_topic: "victron_env/N/c0619ab3baad/solarcharger/289/State"
  icon: mdi:wave-undercurrent
  value_template: >
    {% if value_json.value == 0 %}
      Off
    {% elif value_json.value == 2 %}
      Fault
    {% elif value_json.value == 3 %}
      Bulk
    {% elif value_json.value == 4 %}
      Absorption
    {% elif value_json.value == 5 %}
      Float
    {% elif value_json.value == 6 %}
      Storage
    {% elif value_json.value == 7 %}
      Equalize
    {% else %}
      Error - No Data
    {% endif %}
  device: {
    identifiers: [
      "Victron MPPT 150/70"
    ],
    manufacturer: "Victron Energy",
    model: "MPPT 150/70",
    name: "MPPT 150/70 - GarageSouth"}   


###################################################################################
###################################################################################
# MPPT GarageNorth 150-70 (SmartSolar MPPT VE.Can 150/70 rev2)
###################################################################################

# MPPT GarageNorth - Charger DC meassurements
###################################################################################
- unique_id: victron_solar_charger_garage_north_voltage_battery
  name: DC Voltage
  state_class: measurement
  device_class: voltage
  unit_of_measurement: V
  state_topic: "victron_env/N/c0619ab3baad/solarcharger/290/Dc/0/Voltage"
  value_template: "{{ value_json.value | round(2) }}"
  icon: mdi:lightning-bolt-circle
  device: {
    identifiers: [
      "Victron MPPT 150/70tr"
    ],
    manufacturer: "Victron Energy",
    model: "MPPT 150/70tr",
    name: "MPPT 150/70tr - GarageNorth"}      

- unique_id: victron_solar_charger_garage_north_dc_current
  name: DC Current
  state_class: measurement
  device_class: current
  unit_of_measurement: A
  state_topic: "victron_env/N/c0619ab3baad/solarcharger/290/Dc/0/Current"
  value_template: "{{ value_json.value | round(2) }}"
  icon: mdi:current-dc
  device: {
    identifiers: [
      "Victron MPPT 150/70tr"
    ],
    manufacturer: "Victron Energy",
    model: "MPPT 150/70tr",
    name: "MPPT 150/70tr - GarageNorth"} 

# # MPPT GarageNorth - Photo Voltaic meassurements
# ###################################################################################
- unique_id: victron_solar_charger_garage_north_pv_voltage
  name: PV Voltage
  state_class: measurement
  device_class: voltage
  unit_of_measurement: V
  state_topic: "victron_env/N/c0619ab3baad/solarcharger/290/Pv/V"
  value_template: >
    {% if value_json.value | is_number %}
      {{ value_json.value | round(2) }}
    {% endif %}       
  icon: mdi:lightning-bolt-circle
  device: {
    identifiers: [
      "Victron MPPT 150/70tr"
    ],
    manufacturer: "Victron Energy",
    model: "MPPT 150/70tr",
    name: "MPPT 150/70tr - GarageNorth"}      

# 2024-08-04-This do not exists in the cerboGX venusOS version, only in raspberry venusOS version.
# - unique_id: victron_solar_charger_garage_north_pv_current
#   name:  PV Current
#   state_class: measurement
#   device_class: current
#   unit_of_measurement: A
#   state_topic: "victron_env/N/c0619ab3baad/solarcharger/290/Pv/I"
#   value_template: "{{ value_json.value | round(2) }}"
#   icon: mdi:current-dc
#   device: {
#     identifiers: [
#       "Victron MPPT 150/70tr"
#     ],
#     manufacturer: "Victron Energy",
#     model: "MPPT 150/70tr",
#     name: "MPPT 150/70tr - GarageNorth"}     

- unique_id: victron_solar_charger_garage_north_pv_power
  name: PV Power
  state_class: measurement
  device_class: power
  unit_of_measurement: W
  state_topic: "victron_env/N/c0619ab3baad/solarcharger/290/Yield/Power"
  value_template: >
    {% if value_json.value | is_number %}
      {{ value_json.value | round(2) }}
    {% endif %}  
  icon: mdi:solar-power
  device: {
    identifiers: [
      "Victron MPPT 150/70tr"
    ],
    manufacturer: "Victron Energy",
    model: "MPPT 150/70tr",
    name: "MPPT 150/70tr - GarageNorth"}       

# MPPT GarageNorth - Charger state 
###################################################################################
- unique_id: victron_solar_charger_garage_north_charger_state
  name: Charger State
  state_topic: "victron_env/N/c0619ab3baad/solarcharger/290/State"
  icon: mdi:wave-undercurrent  
  value_template: >
    {% if value_json.value == 0 %}
      Off
    {% elif value_json.value == 2 %}
      Fault
    {% elif value_json.value == 3 %}
      Bulk
    {% elif value_json.value == 4 %}
      Absorption
    {% elif value_json.value == 5 %}
      Float
    {% elif value_json.value == 6 %}
      Storage
    {% elif value_json.value == 7 %}
      Equalize
    {% else %}
      Error - No Data
    {% endif %}
  device: {
    identifiers: [
      "Victron MPPT 150/70tr"
    ],
    manufacturer: "Victron Energy",
    model: "MPPT 150/70tr",
    name: "MPPT 150/70tr - GarageNorth"}  


# victron_env/N/c0619ab3baad/battery/290/Soc


# victron_env/N/c0619ab3baad/battery/290/Dc/0/Voltage
# victron_env/N/c0619ab3baad/battery/290/Dc/0/Current