###################################################################################
###################################################################################
binary_sensor:
###################################################################################
  - platform: group
    name: "Group Garage"
    device_class: opening
    entities:
      - binary_sensor.06_snzb_04_garageoutdoor_door_opening
