###################################################################################
###################################################################################
timer:
###################################################################################
  timer_shutdown_3dprinter_chispi:
    name: Timer Shutdown 3DPrinter Chispi
    icon: mdi:camera-timer
    duration: "00:10:00"
    restore: true

###################################################################################
###################################################################################

input_boolean:
  input_bolean_tgle_chispia10m_service:
    name: input_bolean-tgle-ChispiA10M-service
    icon: mdi:room-service
    #initial: "off" 

###################################################################################
###################################################################################

counter:
  counter_chispia10m_numberofservices:
    name: Counter-ChispiA10M-NumberOfServices
    icon: mdi:wrench-outline
    #initial: 0
    step: 1
    minimum: 0  

###################################################################################
###################################################################################
# To check the utility meters, go to Settings/Devices&Services/Entities.  In the tab Helpers this will not appear.
utility_meter:
###################################################################################
  utility_meter_chispia10m_daily:
    name: UtilityMeter-ChispiA10M-Daily
    # icon: mdi:calendar-today
    source: sensor.hist_stats_chispia10m_total_printing_time_today
    cycle: daily
    offset: 0
    tariffs: []      
    delta_values: false
    net_consumption: false
    periodically_resetting: true   

  utility_meter_chispia10m_weekly:
    name: UtilityMeter-ChispiA10M-Weekly
    # icon: mdi:calendar-today
    source: sensor.hist_stats_chispia10m_total_printing_time_today
    cycle: weekly
    offset: 0
    tariffs: []      
    delta_values: false
    net_consumption: false
    periodically_resetting: true     

  utility_meter_chispia10m_monthly:
    name: UtilityMeter-ChispiA10M-Monthly
    # icon: mdi:calendar-today
    source: sensor.hist_stats_chispia10m_total_printing_time_today
    cycle: monthly
    offset: 0
    tariffs: []      
    delta_values: false
    net_consumption: false
    periodically_resetting: true 

  utility_meter_chispia10m_yearly:
    name: UtilityMeter-ChispiA10M-Yearly
    # icon: mdi:calendar-today
    source: sensor.hist_stats_chispia10m_total_printing_time_today
    cycle: yearly
    offset: 0
    tariffs: []      
    delta_values: false
    net_consumption: false
    periodically_resetting: true     

  utility_meter_chispia10m_servicehours:
    name: UtilityMeter-ChispiA10M-ServiceHours
    # icon: mdi:calendar-today
    source: sensor.hist_stats_chispia10m_total_printing_time_today
    # cycle: none
    delta_values: false
    net_consumption: false
    tariffs: []
    periodically_resetting: true 

####################################################################################
####################################################################################
automation:
####################################################################################
  - alias: Octoprint-ChispiA10M Start timer to switch off
    description: ''
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.chispia10m_octoprint_printing
        from: "on"
        to: "off"
    action:
      - service: timer.start
        data: {}            
        target:
          entity_id: timer.timer_shutdown_3dprinter_chispi
    mode: single

####################################################################################

  - alias: Octoprint-ChispiA10M SwitchOff sonOff
    description: ''
    trigger:
      - platform: state
        entity_id:
          - timer.timer_shutdown_3dprinter_chispi
        to: idle
    condition:
      - condition: and
        conditions:
          - condition: device
            type: is_on
            device_id: 5caef4be13eba001bf7a2758086fa139
            entity_id: switch.07_basicr2_chispia10m
            domain: switch
          - condition: state
            entity_id: binary_sensor.chispia10m_octoprint_printing
            state: "off"
    action:
    - type: turn_off
      device_id: 5caef4be13eba001bf7a2758086fa139
      entity_id: switch.07_basicr2_chispia10m
      domain: switch
    - service: notify.ha_rabbitbot
      data:
        message: ChispiA10M-Octoprint SwitchOff sonOff
        title: End up printing and 10min delay
    mode: single  

####################################################################################

  - alias: Octoprint-ChispiA10M ServiceNeed Activate
    description: ''
    trigger:
    - platform: numeric_state
      entity_id: sensor.utility_meter_chispia10m_servicehours
      above: input_number.number_3dprinters_maxservicehours
    condition: []
    action:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.input_bolean_tgle_chispia10m_service
    - service: telegram_bot.send_message
      data:
        message: ChispiA10M need a maintenance!!!!
        title: ChispiA10M need a maintenance!!!!
    mode: single
####################################################################################

  - alias: Octoprint-ChispiA10M Reset ServicesHours
    description: ''
    trigger:
    - platform: state
      entity_id:
      - input_boolean.input_bolean_tgle_chispia10m_service
      from: 'on'
      to: 'off'
    condition: []
    action:
    - service: utility_meter.calibrate
      data:
        value: '0'
      target:
        entity_id: sensor.utility_meter_chispia10m_servicehours
    - service: counter.increment
      data: {}
      target:
        entity_id:
        - counter.counter_chispia10m_numberofservices
    mode: single  