###################################################################################
###################################################################################
timer:
###################################################################################
  timer_shutdown_3dprinter_ita:
    name: Timer Shutdown 3DPrinter Ita
    icon: mdi:camera-timer
    duration: "00:10:00"
    restore: true

###################################################################################
###################################################################################

input_boolean:
  input_bolean_tgle_itaender3_service:
    name: input_bolean-tgle-ItaEnder3-service
    icon: mdi:room-service
    #initial: "off"

###################################################################################
###################################################################################

counter:
  counter_itaender3_numberofservices:
    name: Counter-ItaEnder3-NumberOfServices
    icon: mdi:wrench-outline
    #initial: 0
    step: 1
    minimum: 0

###################################################################################
###################################################################################
# To check the utility meters, go to Settings/Devices&Services/Entities.  In the tab Helpers this will not appear.
utility_meter:
###################################################################################

  utility_meter_itaender3_daily:
    name: UtilityMeter-ItaEnder3-Daily
    # icon: mdi:calendar-today
    source: sensor.hist_stats_itaender3_total_printing_time_today
    cycle: daily
    offset: 0
    tariffs: []      
    delta_values: false
    net_consumption: false
    periodically_resetting: true   

  utility_meter_itaender3_weekly:
    name: UtilityMeter-ItaEnder3-Weekly
    # icon: mdi:calendar-today
    source: sensor.hist_stats_itaender3_total_printing_time_today
    cycle: weekly
    offset: 0
    tariffs: []      
    delta_values: false
    net_consumption: false
    periodically_resetting: true     

  utility_meter_itaender3_monthly:
    name: UtilityMeter-ItaEnder3-Monthly
    # icon: mdi:calendar-today
    source: sensor.hist_stats_itaender3_total_printing_time_today
    cycle: monthly
    offset: 0
    tariffs: []      
    delta_values: false
    net_consumption: false
    periodically_resetting: true 

  utility_meter_itaender3_yearly:
    name: UtilityMeter-ItaEnder3-Yearly
    # icon: mdi:calendar-today
    source: sensor.hist_stats_itaender3_total_printing_time_today
    cycle: yearly
    offset: 0
    tariffs: []      
    delta_values: false
    net_consumption: false
    periodically_resetting: true     

  utility_meter_itaender3_servicehours:
    name: UtilityMeter-ItaEnder3-ServiceHours
    # icon: mdi:calendar-today
    source: sensor.hist_stats_itaender3_total_printing_time_today
    # cycle: none
    delta_values: false
    net_consumption: false
    tariffs: []
    periodically_resetting: true  

####################################################################################
####################################################################################
automation:
####################################################################################
  - alias: Octoprint-ItaEnder3 Start timer to switch off
    description: ''
    trigger:
      - platform: state
        entity_id:
          - binary_sensor.itaender3_octoprint_printing
        from: "on"
        to: "off"
    action:
      - service: timer.start
        data: {}            
        target:
          entity_id: timer.timer_shutdown_3dprinter_ita
    mode: single

####################################################################################

  - alias: Octoprint-ItaEnder3 SwitchOff sonOff
    description: ''
    trigger:
      - platform: state
        entity_id:
          - timer.timer_shutdown_3dprinter_ita
        to: idle
    condition:
      - condition: and
        conditions:
          - condition: device
            type: is_on
            device_id: a799c084b21a0568a8a43c9452102c80
            entity_id: switch.01_basicr2_itaender3
            domain: switch
          - condition: state
            entity_id: binary_sensor.itaender3_octoprint_printing
            state: "off"
    action:
    - type: turn_off
      device_id: a799c084b21a0568a8a43c9452102c80
      entity_id: switch.01_basicr2_itaender3
      domain: switch
    - service: notify.ha_rabbitbot
      data:
        message: ItaEnder3-Octoprint SwitchOff sonOff
        title: End up printing and 10min delay
    mode: single    

####################################################################################
  
  - alias: Octoprint-ItaEnder3-ServiceNeed-Activate
    description: ''
    trigger:
    - platform: numeric_state
      entity_id: sensor.utilitymeter_itaender3_servicehours
      above: input_number.number_3dprinters_maxservicehours
    condition: []
    action:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.input_bolean_tgle_itaender3_service
    - service: telegram_bot.send_message
      data:
        message: ItaEnder3 need a maintenance!!!!
        title: ItaEnder3 need a maintenance!!!!
    mode: single
####################################################################################

  - alias: Octoprint-ItaEnder3-Reset-ServicesHours
    description: ''
    trigger:
    - platform: state
      entity_id:
      - input_boolean.input_bolean_tgle_itaender3_service
      from: 'on'
      to: 'off'
    condition: []
    action:
    - service: utility_meter.calibrate
      data:
        value: '0'
      target:
        entity_id: sensor.utilitymeter_itaender3_servicehours
    - service: counter.increment
      data: {}
      target:
        entity_id:
        - counter.counter_itaender3_numberofservices
    mode: single  
    
